In [1]:
import pandas as pd
import datetime
from datetime import timedelta

In [5]:
pd.set_option('display.max_rows', 500)

In [4]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,11/09/2019,03:00:00,REGULAR,7265644.0,2462047.0
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,11/09/2019,07:00:00,REGULAR,7265653.0,2462059.0
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,11/09/2019,11:00:00,REGULAR,7265724.0,2462131.0
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,11/09/2019,15:00:00,REGULAR,7265931.0,2462199.0
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,11/09/2019,19:00:00,REGULAR,7266259.0,2462265.0

In [36]:
stations = set({})

In [37]:
len(stations)

0

In [18]:
path_prefix = "/Users/candide/Acads/EDAV/final project/turnstile_data/"

In [64]:
d = datetime.date(2019, 12, 7)
for i in range(52,0,-1):
    s = d.strftime('%Y%m%d')
    file_path = path_prefix + s + ".csv"
    df = pd.read_csv(file_path)
    stations_current = set(df.STATION.unique())
    stations = stations.union(stations_current)
    d = d - timedelta(days=7)

In [82]:
stations

{'1 AV',
 '103 ST',
 '103 ST-CORONA',
 '104 ST',
 '110 ST',
 '111 ST',
 '116 ST',
 '116 ST-COLUMBIA',
 '121 ST',
 '125 ST',
 '135 ST',
 '137 ST CITY COL',
 '138/GRAND CONC',
 '14 ST',
 '14 ST-UNION SQ',
 '145 ST',
 '149/GRAND CONC',
 '14TH STREET',
 '15 ST-PROSPECT',
 '155 ST',
 '157 ST',
 '161/YANKEE STAD',
 '163 ST-AMSTERDM',
 '167 ST',
 '168 ST',
 '169 ST',
 '170 ST',
 '174 ST',
 '174-175 STS',
 '175 ST',
 '176 ST',
 '18 AV',
 '18 ST',
 '181 ST',
 '182-183 STS',
 '183 ST',
 '190 ST',
 '191 ST',
 '2 AV',
 '20 AV',
 '207 ST',
 '21 ST',
 '21 ST-QNSBRIDGE',
 '215 ST',
 '219 ST',
 '225 ST',
 '23 ST',
 '231 ST',
 '233 ST',
 '238 ST',
 '25 AV',
 '25 ST',
 '28 ST',
 '3 AV',
 '3 AV 138 ST',
 '3 AV-149 ST',
 '30 AV',
 '33 ST',
 '33 ST-RAWSON ST',
 '34 ST-HERALD SQ',
 '34 ST-HUDSON YD',
 '34 ST-PENN STA',
 '36 AV',
 '36 ST',
 '39 AV',
 '4 AV-9 ST',
 '40 ST LOWERY ST',
 '42 ST-BRYANT PK',
 '42 ST-PORT AUTH',
 '45 ST',
 '46 ST',
 '46 ST BLISS ST',
 '47-50 STS ROCK',
 '49 ST',
 '4AV-9 ST',
 '5 AV/53 ST',
 '5 AV/59 ST',
 '5 AVE',
 '50 ST',
 '51 ST',
 '52 ST',
 '53 ST',
 '55 ST',
 '57 ST',
 '57 ST-7 AV',
 '59 ST',
 '59 ST COLUMBUS',
 '6 AV',
 '61 ST WOODSIDE',
 '63 DR-REGO PARK',
 '65 ST',
 '66 ST-LINCOLN',
 '67 AV',
 '68ST-HUNTER CO',
 '69 ST',
 '7 AV',
 '71 ST',
 '72 ST',
 '72 ST-2 AVE',
 '74 ST-BROADWAY',
 '75 AV',
 '75 ST-ELDERTS',
 '77 ST',
 '79 ST',
 '8 AV',
 '8 ST-NYU',
 '80 ST',
 '81 ST-MUSEUM',
 '82 ST-JACKSON H',
 '85 ST-FOREST PK',
 '86 ST',
 '86 ST-2 AVE',
 '88 ST',
 '9 AV',
 '90 ST-ELMHURST',
 '96 ST',
 '96 ST-2 AVE',
 '9TH STREET',
 'ALABAMA AV',
 'ALLERTON AV',
 'AQUEDUCT N.COND',
 'AQUEDUCT RACETR',
 'ASTOR PL',
 'ASTORIA BLVD',
 'ASTORIA DITMARS',
 'ATL AV-BARCLAY',
 'ATLANTIC AV',
 'AVENUE H',
 'AVENUE I',
 'AVENUE J',
 'AVENUE M',
 'AVENUE N',
 'AVENUE P',
 'AVENUE U',
 'AVENUE X',
 "B'WAY-LAFAYETTE",
 'BAY 50 ST',
 'BAY PKWY',
 'BAY RIDGE AV',
 'BAY RIDGE-95 ST',
 'BAYCHESTER AV',
 'BEACH 105 ST',
 'BEACH 25 ST',
 'BEACH 36 ST',
 'BEACH 44 ST',
 'BEACH 60 ST',
 'BEACH 67 ST',
 'BEACH 90 ST',
 'BEACH 98 ST',
 'BEDFORD AV',
 'BEDFORD PK BLVD',
 'BEDFORD-NOSTRAN',
 'BERGEN ST',
 'BEVERLEY ROAD',
 'BEVERLY RD',
 'BLEECKER ST',
 'BOROUGH HALL',
 'BOTANIC GARDEN',
 'BOWERY',
 'BOWLING GREEN',
 'BRIARWOOD',
 'BRIGHTON BEACH',
 'BROAD CHANNEL',
 'BROAD ST',
 'BROADWAY',
 'BROADWAY JCT',
 'BRONX PARK EAST',
 'BROOK AV',
 'BROOKLYN BRIDGE',
 'BUHRE AV',
 'BURKE AV',
 'BURNSIDE AV',
 'BUSHWICK AV',
 'CANAL ST',
 'CANARSIE-ROCKAW',
 'CARROLL ST',
 'CASTLE HILL AV',
 'CATHEDRAL PKWY',
 'CENTRAL AV',
 'CENTRAL PK N110',
 'CHAMBERS ST',
 'CHAUNCEY ST',
 'CHRISTOPHER ST',
 'CHURCH AV',
 'CITY / BUS',
 'CITY HALL',
 'CLARK ST',
 'CLASSON AV',
 'CLEVELAND ST',
 'CLINTON-WASH AV',
 'CONEY IS-STILLW',
 'CORTELYOU RD',
 'CORTLANDT ST',
 'COURT SQ',
 'COURT SQ-23 ST',
 'CRESCENT ST',
 'CROWN HTS-UTICA',
 'CYPRESS AV',
 'CYPRESS HILLS',
 'DEKALB AV',
 'DELANCEY/ESSEX',
 'DITMAS AV',
 'DYCKMAN ST',
 "E 143/ST MARY'S",
 'E 149 ST',
 'E 180 ST',
 'EAST 105 ST',
 'EAST BROADWAY',
 'EASTCHSTER/DYRE',
 'EASTN PKWY-MUSM',
 'ELDER AV',
 'ELMHURST AV',
 'EUCLID AV',
 'EXCHANGE PLACE',
 'FAR ROCKAWAY',
 'FLATBUSH AV-B.C',
 'FLUSHING AV',
 'FLUSHING-MAIN',
 'FORDHAM RD',
 'FOREST AVE',
 'FOREST HILLS 71',
 'FRANKLIN AV',
 'FRANKLIN ST',
 'FREEMAN ST',
 'FRESH POND RD',
 'FT HAMILTON PKY',
 'FULTON ST',
 'GATES AV',
 'GRAHAM AV',
 'GRAND ARMY PLAZ',
 'GRAND ST',
 'GRAND-NEWTOWN',
 'GRANT AV',
 'GRD CNTRL-42 ST',
 'GREENPOINT AV',
 'GROVE STREET',
 'GUN HILL RD',
 'HALSEY ST',
 'HARLEM 148 ST',
 'HARRISON',
 'HEWES ST',
 'HIGH ST',
 'HOUSTON ST',
 'HOWARD BCH JFK',
 'HOYT ST',
 'HOYT-SCHER',
 'HUNTERS PT AV',
 'HUNTS POINT AV',
 'INTERVALE AV',
 'INWOOD-207 ST',
 'JACKSON AV',
 'JAMAICA 179 ST',
 'JAMAICA CENTER',
 'JAMAICA VAN WK',
 'JAY ST-METROTEC',
 'JEFFERSON ST',
 'JFK JAMAICA CT1',
 'JKSN HT-ROOSVLT',
 'JOURNAL SQUARE',
 'JUNCTION BLVD',
 'JUNIUS ST',
 'KEW GARDENS',
 'KINGS HWY',
 'KINGSBRIDGE RD',
 'KINGSTON AV',
 'KINGSTON-THROOP',
 'KNICKERBOCKER',
 'KOSCIUSZKO ST',
 'LACKAWANNA',
 'LAFAYETTE AV',
 'LEXINGTON AV/53',
 'LEXINGTON AV/63',
 'LIBERTY AV',
 'LIVONIA AV',
 'LONGWOOD AV',
 'LORIMER ST',
 'MARBLE HILL-225',
 'MARCY AV',
 'METROPOLITAN AV',
 'METS-WILLETS PT',
 'MIDDLETOWN RD',
 'MONTROSE AV',
 'MORGAN AV',
 'MORISN AV/SNDVW',
 'MORRIS PARK',
 'MOSHOLU PKWY',
 'MT EDEN AV',
 'MYRTLE AV',
 'MYRTLE-WILLOUGH',
 'MYRTLE-WYCKOFF',
 'NASSAU AV',
 'NECK RD',
 'NEPTUNE AV',
 'NEREID AV',
 'NEVINS ST',
 'NEW LOTS',
 'NEW LOTS AV',
 'NEW UTRECHT AV',
 'NEWARK BM BW',
 'NEWARK C',
 'NEWARK HM HE',
 'NEWARK HW BMEBE',
 'NEWKIRK AV',
 'NEWKIRK PLAZA',
 'NORTHERN BLVD',
 'NORWOOD 205 ST',
 'NORWOOD AV',
 'NOSTRAND AV',
 'OCEAN PKWY',
 'ORCHARD BEACH',
 'OZONE PK LEFFRT',
 'PARK PLACE',
 'PARKCHESTER',
 'PARKSIDE AV',
 'PARSONS BLVD',
 'PATH NEW WTC',
 'PATH WTC 2',
 'PAVONIA/NEWPORT',
 'PELHAM BAY PARK',
 'PELHAM PKWY',
 'PENNSYLVANIA AV',
 'PRESIDENT ST',
 'PRINCE ST',
 'PROSPECT AV',
 'PROSPECT PARK',
 'QUEENS PLAZA',
 'QUEENSBORO PLZ',
 'RALPH AV',
 'RECTOR ST',
 'RIT-MANHATTAN',
 'RIT-ROOSEVELT',
 'ROCKAWAY AV',
 'ROCKAWAY BLVD',
 'ROCKAWAY PARK B',
 'ROOSEVELT ISLND',
 'SARATOGA AV',
 'SENECA AVE',
 'SHEEPSHEAD BAY',
 'SHEPHERD AV',
 'SIMPSON ST',
 'SMITH-9 ST',
 'SOUTH FERRY',
 'SPRING ST',
 'ST LAWRENCE AV',
 'ST. GEORGE',
 'STEINWAY ST',
 'STERLING ST',
 'SUTPHIN BLVD',
 'SUTPHIN-ARCHER',
 'SUTTER AV',
 'SUTTER AV-RUTLD',
 'THIRTY ST',
 'THIRTY THIRD ST',
 'TIMES SQ-42 ST',
 'TOMPKINSVILLE',
 'TREMONT AV',
 'TWENTY THIRD ST',
 'UNION ST',
 'UTICA AV',
 'V.CORTLANDT PK',
 'VAN SICLEN AV',
 'VAN SICLEN AVE',
 'VERNON-JACKSON',
 'W 4 ST-WASH SQ',
 'W 8 ST-AQUARIUM',
 'WAKEFIELD/241',
 'WALL ST',
 'WEST FARMS SQ',
 'WESTCHESTER SQ',
 'WHITEHALL S-FRY',
 'WHITLOCK AV',
 'WILSON AV',
 'WINTHROP ST',
 'WOODHAVEN BLVD',
 'WOODLAWN',
 'WORLD TRADE CTR',
 'WTC-CORTLANDT',
 'YORK ST',
 'ZEREGA AV'}

In [41]:
def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

numbered_stations = []

for station_name in stations:
    if hasNumbers(station_name):
        numbered_stations.append(station_name)

In [133]:
stations_info = pd.read_csv("/Users/candide/Acads/EDAV/final project/turnstile_data/stations.csv")

In [134]:
manhattan_stations = list(stations_info[stations_info["Borough"] == "M"]["Stop Name"].unique())

In [150]:
sorted(manhattan_stations)

['1 Av',
 '103 St',
 '110 St',
 '116 St',
 '116 St - Columbia University',
 '125 St',
 '135 St',
 '137 St - City College',
 '14 St',
 '14 St - Union Sq',
 '145 St',
 '155 St',
 '157 St',
 '163 St - Amsterdam Av',
 '168 St',
 '168 St - Washington Hts',
 '175 St',
 '18 St',
 '181 St',
 '190 St',
 '191 St',
 '2 Av',
 '207 St',
 '215 St',
 '23 St',
 '28 St',
 '3 Av',
 '33 St',
 '34 St - 11 Av',
 '34 St - Herald Sq',
 '34 St - Penn Station',
 '42 St - Bryant Pk',
 '42 St - Port Authority Bus Terminal',
 '47-50 Sts - Rockefeller Ctr',
 '49 St',
 '5 Av',
 '5 Av/53 St',
 '5 Av/59 St',
 '50 St',
 '51 St',
 '57 St',
 '57 St - 7 Av',
 '59 St',
 '59 St - Columbus Circle',
 '6 Av',
 '66 St - Lincoln Center',
 '68 St - Hunter College',
 '7 Av',
 '72 St',
 '77 St',
 '79 St',
 '8 Av',
 '8 St - NYU',
 '81 St - Museum of Natural History',
 '86 St',
 '96 St',
 'Astor Pl',
 'Bleecker St',
 'Bowery',
 'Bowling Green',
 'Broad St',
 'Broadway-Lafayette St',
 'Brooklyn Bridge - City Hall',
 'Canal St',
 'Cathedral Pkwy',
 'Cathedral Pkwy (110 St)',
 'Central Park North (110 St)',
 'Chambers St',
 'Christopher St - Sheridan Sq',
 'City Hall',
 'Cortlandt St',
 'Delancey St',
 'Dyckman St',
 'East Broadway',
 'Essex St',
 'Franklin St',
 'Fulton St',
 'Grand Central - 42 St',
 'Grand St',
 'Harlem - 148 St',
 'Houston St',
 'Inwood - 207 St',
 'Lexington Av/53 St',
 'Lexington Av/59 St',
 'Lexington Av/63 St',
 'Marble Hill - 225 St',
 'Park Pl',
 'Prince St',
 'Rector St',
 'Roosevelt Island',
 'South Ferry',
 'Spring St',
 'Times Sq - 42 St',
 'Union Sq - 14 St',
 'W 4 St',
 'WTC Cortlandt',
 'Wall St',
 'Whitehall St',
 'World Trade Center']

In [136]:
len(manhattan_stations)

99

In [87]:
!pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading https://files.pythonhosted.org/packages/d8/f1/5a267addb30ab7eaa1beab2b9323073815da4551076554ecc890a3595ec9/fuzzywuzzy-0.17.0-py2.py3-none-any.whl
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.17.0

In [103]:
from fuzzywuzzy import process

In [117]:
matches = {}
for station_name in manhattan_stations:
    result = process.extract(station_name, stations, limit=2)
    if result[0][1] > 90:
        matches[station_name] = result[0][0]
    else:
        matches[station_name] = ""

In [118]:
matches

{'Lexington Av/59 St': '',
 '5 Av/59 St': '5 AV/59 ST',
 '57 St - 7 Av': '57 ST-7 AV',
 '49 St': '49 ST',
 'Times Sq - 42 St': 'TIMES SQ-42 ST',
 '34 St - Herald Sq': '34 ST-HERALD SQ',
 '28 St': '28 ST',
 '23 St': '23 ST',
 '14 St - Union Sq': '14 ST-UNION SQ',
 '8 St - NYU': '8 ST-NYU',
 'Prince St': 'PRINCE ST',
 'Canal St': 'CANAL ST',
 'City Hall': 'CITY HALL',
 'Cortlandt St': 'CORTLANDT ST',
 'Rector St': 'RECTOR ST',
 'Whitehall St': '',
 'Essex St': '',
 'Bowery': 'BOWERY',
 'Chambers St': 'CHAMBERS ST',
 'Fulton St': 'FULTON ST',
 'Broad St': 'BROAD ST',
 '8 Av': '8 AV',
 '6 Av': '6 AV',
 'Union Sq - 14 St': '14 ST-UNION SQ',
 '3 Av': '3 AV',
 '1 Av': '1 AV',
 'Inwood - 207 St': 'INWOOD-207 ST',
 'Dyckman St': 'DYCKMAN ST',
 '190 St': '190 ST',
 '181 St': '181 ST',
 '175 St': '175 ST',
 '168 St': '168 ST',
 '163 St - Amsterdam Av': '',
 '155 St': '155 ST',
 '145 St': '145 ST',
 '135 St': '135 ST',
 '125 St': '125 ST',
 '116 St': '116 ST',
 'Cathedral Pkwy (110 St)': '',
 '103 St': '103 ST',
 '96 St': '96 ST',
 '86 St': '86 ST',
 '81 St - Museum of Natural History': '',
 '72 St': '72 ST',
 '59 St - Columbus Circle': '',
 '50 St': '50 ST',
 '42 St - Port Authority Bus Terminal': '',
 '34 St - Penn Station': '',
 '14 St': '14 ST',
 'W 4 St': '',
 'Spring St': 'SPRING ST',
 'World Trade Center': 'WORLD TRADE CTR',
 'Roosevelt Island': 'ROOSEVELT ISLND',
 'Lexington Av/63 St': 'LEXINGTON AV/63',
 '57 St': '57 ST',
 '47-50 Sts - Rockefeller Ctr': '',
 '42 St - Bryant Pk': '42 ST-BRYANT PK',
 'Broadway-Lafayette St': '',
 'Grand St': 'GRAND ST',
 '2 Av': '2 AV',
 'Delancey St': '',
 'East Broadway': 'EAST BROADWAY',
 'Lexington Av/53 St': 'LEXINGTON AV/53',
 '5 Av/53 St': '5 AV/53 ST',
 '7 Av': '7 AV',
 'Marble Hill - 225 St': 'MARBLE HILL-225',
 '215 St': '215 ST',
 '207 St': '207 ST',
 '191 St': '191 ST',
 '168 St - Washington Hts': '',
 '157 St': '157 ST',
 '137 St - City College': '',
 '116 St - Columbia University': '',
 'Cathedral Pkwy': 'CATHEDRAL PKWY',
 '79 St': '79 ST',
 '66 St - Lincoln Center': '',
 '18 St': '18 ST',
 'Christopher St - Sheridan Sq': '',
 'Houston St': 'HOUSTON ST',
 'Franklin St': 'FRANKLIN ST',
 'WTC Cortlandt': 'WTC-CORTLANDT',
 'South Ferry': 'SOUTH FERRY',
 'Park Pl': '',
 'Wall St': 'WALL ST',
 '110 St': '110 ST',
 '77 St': '77 ST',
 '68 St - Hunter College': '',
 '59 St': '59 ST',
 '51 St': '51 ST',
 'Grand Central - 42 St': '',
 '33 St': '33 ST',
 'Astor Pl': 'ASTOR PL',
 'Bleecker St': 'BLEECKER ST',
 'Brooklyn Bridge - City Hall': '',
 'Bowling Green': 'BOWLING GREEN',
 'Harlem - 148 St': 'HARLEM 148 ST',
 'Central Park North (110 St)': '',
 '5 Av': '',
 '34 St - 11 Av': ''}

In [119]:
non_matches = []
for entry, match in matches.items():
    if not match:
        non_matches.append(entry)

In [120]:
non_matches

['Lexington Av/59 St',
 'Whitehall St',
 'Essex St',
 '163 St - Amsterdam Av',
 'Cathedral Pkwy (110 St)',
 '81 St - Museum of Natural History',
 '59 St - Columbus Circle',
 '42 St - Port Authority Bus Terminal',
 '34 St - Penn Station',
 'W 4 St',
 '47-50 Sts - Rockefeller Ctr',
 'Broadway-Lafayette St',
 'Delancey St',
 '168 St - Washington Hts',
 '137 St - City College',
 '116 St - Columbia University',
 '66 St - Lincoln Center',
 'Christopher St - Sheridan Sq',
 'Park Pl',
 '68 St - Hunter College',
 'Grand Central - 42 St',
 'Brooklyn Bridge - City Hall',
 'Central Park North (110 St)',
 '5 Av',
 '34 St - 11 Av']

In [125]:
# manually filling all unmatched stations, by querying for the names online
matches["Whitehall St"] = 'WHITEHALL S-FRY'
matches["Essex St"] = 'DELANCEY/ESSEX'
matches["163 St - Amsterdam Av"] = '163 ST-AMSTERDM'
matches["Cathedral Pkwy (110 St)"] = 'CATHEDRAL PKWY'
matches["81 St - Museum of Natural History"] = '81 ST-MUSEUM'
matches["59 St - Columbus Circle"] = '59 ST COLUMBUS'
matches["42 St - Port Authority Bus Terminal"] = '42 ST-PORT AUTH'
matches["34 St - Penn Station"] = '34 ST-PENN STA'
matches["47-50 Sts - Rockefeller Ctr"] = '47-50 STS ROCK'
matches["W 4 St"] = 'W 4 ST-WASH SQ'
matches["137 St - City College"] = '137 ST CITY COL'
matches["116 St - Columbia University"] = '116 ST-COLUMBIA'
matches["66 St - Lincoln Center"] = '66 ST-LINCOLN'
matches["Christopher St - Sheridan Sq"] = 'CHRISTOPHER ST'
matches["Park Pl"] = 'PARK PLACE'
matches["68 St - Hunter College"] = '68ST-HUNTER CO'
matches["Grand Central - 42 St"] = 'GRD CNTRL-42 ST'
matches["Brooklyn Bridge - City Hall"] = 'BROOKLYN BRIDGE'
matches["Central Park North (110 St)"] = 'CENTRAL PK N110'
matches["5 Av"] = '5 AVE'
matches["34 St - 11 Av"] = '34 ST-HUDSON YD'
matches["Broadway-Lafayette St"] = 'BLEECKER ST'

In [126]:
non_matches_re = []
for entry, match in matches.items():
    if not match:
        non_matches_re.append(entry)

In [127]:
# no match for these st. names taken from the Subway info file on MTA website to st. names in turnstile data
non_matches_re

['Lexington Av/59 St', 'Delancey St', '168 St - Washington Hts']

In [128]:
len(matches)

99

In [138]:
matches = dict((k, v) for k, v in matches.items() if v)

In [153]:
names = list(set(list(matches.values())))

In [154]:
len(names)

93

In [155]:
manhattan_stations_df = pd.DataFrame({"STATION":names})

In [53]:
df = pd.read_csv('/Users/candide/Acads/EDAV/final project/turnstile_data/20181215.csv')

In [165]:
df.DESC.value_counts()

REGULAR       200128
RECOVR AUD       734
Name: DESC, dtype: int64

In [167]:
df.columns.values

array(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE',
       'TIME', 'DESC', 'ENTRIES',
       'EXITS                                                               ',
       'DATETIME'], dtype=object)

In [188]:
df1 = pd.DataFrame(columns=['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'ENTRIES', 'EXITS', 'DATETIME'])
d = datetime.date(2019, 12, 7)
for i in range(52,0,-1):
    s = d.strftime('%Y%m%d')
    file_path = path_prefix + s + ".csv"
    df = pd.read_csv(file_path)
    df.rename(columns={'EXITS                                                               ':'EXITS'}, inplace=True)
    df = df[df["DESC"] == "REGULAR"]
    df = df.merge(manhattan_stations_df, on="STATION", how="inner")
    df["DATETIME"] = df.DATE + " " + df.TIME
    df["DATETIME"] = df["DATETIME"].apply(lambda x: datetime.datetime.strptime(x, "%m/%d/%Y %H:%M:%S"))
    df.drop(columns=["DATE", "TIME", "DESC"], inplace=True)
    df.sort_values('DATETIME', ascending=False, inplace=True)
    df1 = pd.concat([df1, df], ignore_index=True, copy=False)
    d = d - timedelta(days=7)

In [16]:
d = datetime.date(2018, 12, 8)

In [21]:
# get one previous entry for all the turnstiles to help the diff of cumulative counts
s = d.strftime('%Y%m%d')
file_path = path_prefix + s + ".csv"
df = pd.read_csv(file_path)
df.rename(columns={'EXITS                                                               ':'EXITS'}, inplace=True)
df = df[df["DESC"] == "REGULAR"]
df = df.merge(manhattan_stations_df, on="STATION", how="inner")
df["DATETIME"] = df.DATE + " " + df.TIME
df["DATETIME"] = df["DATETIME"].apply(lambda x: datetime.datetime.strptime(x, "%m/%d/%Y %H:%M:%S"))
df.drop(columns=["DATE", "TIME", "DESC"], inplace=True)
timestampzero = df.loc[df.groupby('STATION')['DATETIME'].idxmax()]

In [33]:
len(df)

88570

In [24]:
timestampzero

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,ENTRIES,EXITS,DATETIME
36642,H007,R248,00-00-00,1 AV,L,BMT,14202153,15924834,2018-12-07 23:00:00
46406,N037,R314,00-00-00,103 ST,BC,IND,13821697,11165893,2018-12-07 20:00:00
86195,R253,R181,00-00-00,110 ST,6,IRT,4518410,7212835,2018-12-07 23:00:00
44891,N029,R333,01-00-00,116 ST,BC,IND,168426490,168415228,2018-12-07 20:00:00
75718,R173,R159,00-00-00,116 ST-COLUMBIA,1,IRT,4986283,5539980,2018-12-07 20:00:00
43001,N025,R102,01-00-00,125 ST,ACBD,IND,5763735,4647143,2018-12-07 23:00:00
42489,R306,R207,00-00-00,135 ST,23,IRT,12461568,3322073,2018-12-07 23:00:00
75985,R175,R169,01-00-00,137 ST CITY COL,1,IRT,2786134,16462447,2018-12-07 20:00:00
58600,N510,R163,02-00-00,14 ST,FLM123,IND,4429758,6872351,2018-12-07 23:00:00
12804,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,2034768,5122373,2018-12-07 20:00:00
41201,N019,R101,01-00-00,145 ST,ABCD,IND,7012515,15188361,2018-12-07 23:00:00
40865,N017,R331,00-00-00,155 ST,C,IND,2276487,5178219,2018-12-07 20:00:00
76405,R179,R193,01-00-00,157 ST,1,IRT,3520131,6154190,2018-12-07 20:00:00
40529,N016A,R296,00-00-00,163 ST-AMSTERDM,C,IND,8448852,605125,2018-12-07 20:00:00
39696,N012,R035,01-05-00,168 ST,AC1,IND,131176,589824,2018-12-07 23:00:00
39025,N010,R126,00-00-00,175 ST,A,IND,3751528,5898357,2018-12-07 23:00:00
74461,R129,R321,00-00-00,18 ST,1,IRT,4214461,1541508,2018-12-07 23:00:00
38816,R183,R260,00-00-00,181 ST,1,IRT,3521074,1680009,2018-12-07 23:00:00
38478,N006A,R280,00-00-00,190 ST,A,IND,1442549964,1845240125,2018-12-03 03:00:00
76741,R185,R274,00-00-00,191 ST,1,IRT,2143762,4782128,2018-12-07 23:00:00
66710,N521,R300,01-00-00,2 AV,F,IND,8784486,9878095,2018-12-07 23:00:00
76909,R188,R037,00-00-00,207 ST,1,IRT,9572329,2060633,2018-12-07 23:00:00
77161,R190,R038,00-00-00,215 ST,1,IRT,140128,31043,2018-12-07 23:00:00
9732,A030,R083,01-00-00,23 ST,NRW,BMT,6956330,4472664,2018-12-07 23:00:00
8878,A027,R082,01-00-00,28 ST,NRW,BMT,3250781,3896954,2018-12-07 23:00:00
36390,H005,R330,00-00-00,3 AV,L,BMT,3106392,8633241,2018-12-07 23:00:00
80423,R231,R176,00-00-00,33 ST,6,IRT,5492614,4155451,2018-12-07 20:00:00
8336,N507,R023,00-00-00,34 ST-HERALD SQ,BDFMNQRW,IND,469500,55431176,2018-12-07 23:12:01
87250,R550,R072,00-00-00,34 ST-HUDSON YD,7,IRT,39253,186030,2018-12-07 23:00:00
54024,N067,R012,00-00-00,34 ST-PENN STA,ACE,IND,2164740,2451219,2018-12-07 23:00:00
65819,N502,R021,01-00-00,42 ST-BRYANT PK,BDFM7,IND,1654181,1018523,2018-12-07 23:00:00
52261,N062,R011,01-00-00,42 ST-PORT AUTH,ACENQRS1237W,IND,11545640,39432219,2018-12-07 23:00:00
64241,N500,R020,00-00-00,47-50 STS ROCK,BDFM,IND,147503,280748,2018-12-07 23:00:00
3471,A013,R081,01-00-00,49 ST,NQRW,BMT,5974178,36559164,2018-12-07 23:00:00
62007,N303,R015,00-00-00,5 AV/53 ST,EM,IND,13749488,29714074,2018-12-07 21:00:00
2223,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,3644088,6238800,2018-12-07 21:00:00
86829,R501,R054,00-00-00,5 AVE,7BDFM,IRT,723911,2445051,2018-12-07 23:00:00
34081,E004,R234,00-00-00,50 ST,D,BMT,5619093,5252667,2018-12-07 23:00:00
84640,R242,R049,01-00-00,51 ST,6,IRT,110393,92274,2018-12-07 23:00:00
2836,A010,R080,00-00-00,57 ST-7 AV,NQRW,BMT,3909481,1860131,2018-12-07 23:00:00
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,6863246,2327460,2018-12-07 23:00:00
50127,N049,R084,01-00-00,59 ST COLUMBUS,ABCD1,IND,2862620,11650799,2018-12-07 23:00:00
36181,H003,R163,01-00-00,6 AV,FLM123,BMT,7679595,9494810,2018-12-07 23:00:00
74796,R159,R164,01-00-00,66 ST-LINCOLN,1,IRT,4773406,12092026,2018-12-07 20:00:00
85605,R246,R177,00-00-00,68ST-HUNTER CO,6,IRT,26898195,15502810,2018-12-07 20:00:00
28986,B004,R171,00-00-00,7 AV,BQ,BMT,6518283,4781991,2018-12-07 20:00:00
48983,N046,R281,00-00-00,72 ST,BC,IND,3304766,1760036,2018-12-07 23:00:00
30260,C024,R214,00-00-00,77 ST,R,BMT,8185564,1875475,2018-12-07 23:00:00
35598,E011,R371,00-00-00,79 ST,D,BMT,11052015,8809343,2018-12-07 23:00:00
33398,D002,R390,00-00-00,8 AV,N,BMT,2909185,4408346,2018-12-07 20:00:00
14395,A038,R085,00-00-00,8 ST-NYU,NRW,BMT,3428342,2943269,2018-12-07 23:00:00
48563,N044,R187,00-00-00,81 ST-MUSEUM,BC,IND,7509252,2041497,2018-12-07 20:00:00
31498,N043,R186,00-00-00,86 ST,BC,IND,751239,720517,2018-12-07 23:00:00
47016,N039,R251,01-00-00,96 ST,BC,IND,2207075,743118,2018-12-07 23:00:00
79916,R219,R160,00-00-00,ASTOR PL,6,IRT,4115041,4094930,2018-12-07 20:00:00
79539,R217A,R194,00-00-00,BLEECKER ST,6DF,IRT,2969285,775414,2018-12-07 23:00:00
21986,A064,R311,00-00-00,BOWERY,JZ,BMT,5532754,3898494,2018-12-07 23:00:00
77531,R200A,R041,01-00-00,BOWLING GREEN,45,IRT,9583601,7686228,2018-12-07 23:00:00
28482,A083,R125,00-00-00,BROAD ST,JZ,BMT,5413732,2052264,2018-12-07 20:00:00
78788,R210,R044,00-00-00,BROOKLYN BRIDGE,456JZ,IRT,68256730,68270871,2018-12-07 23:00:00
16729,N089,R139,00-00-00,CANAL ST,ACE,IND,5960726,16014097,2018-12-07 23:00:00
45818,N034,R334,01-00-00,CATHEDRAL PKWY,BC,IND,1987898,982062,2018-12-07 20:00:00
86451,R301,R323,00-00-00,CENTRAL PK N110,23,IRT,2712923,1464497,2018-12-07 23:00:00
22115,A069,R044,01-00-00,CHAMBERS ST,JZ456,BMT,3211872,14510607,2018-12-07 23:00:00
68611,PTH09,R548,00-00-01,CHRISTOPHER ST,1,PTH,526940,455483,2018-12-07 23:48:03
17777,A047,R087,00-00-00,CITY HALL,NRW,BMT,7088872,4337437,2018-12-07 23:00:00
18155,A049,R088,02-00-00,CORTLANDT ST,RNW,BMT,686198,874280,2018-12-07 20:00:00
21187,A061,R142,00-00-00,DELANCEY/ESSEX,FJMZ,BMT,12706398,11549121,2018-12-07 20:00:00
38260,R186,R036,00-00-00,DYCKMAN ST,1,IRT,1444397,1775465,2018-12-07 23:00:00
67147,N528,R257,01-00-00,EAST BROADWAY,F,IND,14746484,8286310,2018-12-07 23:00:00
73501,R117,R343,00-00-00,FRANKLIN ST,1,IRT,9747151,2045053,2018-12-07 12:55:04
26584,N422,R318,00-00-00,FULTON ST,G,IND,6026531,7691335,2018-12-07 23:00:00
37062,H015,R250,01-00-00,GRAND ST,L,BMT,7111828,3930113,2018-12-07 23:00:00
81968,R237,R046,01-00-00,GRD CNTRL-42 ST,4567S,IRT,1245457,3635717,2018-12-07 23:00:00
86703,R309,R345,00-00-00,HARLEM 148 ST,3,IRT,2642489,3999393,2018-12-07 23:00:00
73789,R121,R290,01-03-00,HOUSTON ST,1,IRT,2308627,167889,2018-12-07 20:00:00
37668,N001,R173,01-05-00,INWOOD-207 ST,A,IND,437,0,2018-12-07 20:00:00
62889,N305,R017,01-00-00,LEXINGTON AV/53,EM6,IND,862021,4766197,2018-12-07 23:00:00
67619,N601,R319,00-00-00,LEXINGTON AV/63,F,IND,3568728,11305033,2018-12-07 23:00:00
77327,R192,R039,00-00-00,MARBLE HILL-225,1,IRT,3980719,420097,2018-12-07 23:00:00
30092,R115,R029,00-00-00,PARK PLACE,23ACE,IRT,3235426,4783407,2018-12-07 23:00:00
14913,A041,R086,00-00-00,PRINCE ST,NRW,BMT,11729956,4394303,2018-12-07 23:00:00
19746,A054,R227,01-00-00,RECTOR ST,NRW,BMT,5273480,7715035,2018-12-07 23:00:00
68446,N602,R259,00-00-00,ROOSEVELT ISLND,F,IND,970596,2117330,2018-12-03 07:00:00
68994,R101,R001,02-00-00,SOUTH FERRY,1RW,IRT,3231360,5097501,2018-12-07 20:00:00
60665,N086,R282,00-00-00,SPRING ST,CE,IND,5546058,1425348,2018-12-07 23:00:00
4415,A021,R032,01-00-00,TIMES SQ-42 ST,ACENQRS1237W,BMT,8375719,10194377,2018-12-07 23:00:00
59867,N080,R138,00-00-00,W 4 ST-WASH SQ,ABCDEFM,IND,1525492,4197342,2018-12-07 20:00:00
71416,R110,R027,01-00-00,WALL ST,23,IRT,4319778,6573819,2018-12-07 23:00:00
20560,A058,R001,01-00-00,WHITEHALL S-FRY,R1W,BMT,1476253,3426294,2018-12-07 20:00:00
61253,N094,R029,01-00-00,WORLD TRADE CTR,ACE23,IND,418066,619126,2018-12-07 23:00:00
69934,R106,R305,01-00-00,WTC-CORTLANDT,1,IRT,84,714,2018-12-07 20:00:00

In [200]:
# concatenate this first timestamp with the past one year file
df1 = pd.concat([df1, timestampzero], ignore_index=True, copy=False)

In [36]:
df1.to_csv("cleaned_data_1.csv", index=False)

In [122]:
df1 = pd.read_csv("cleaned_data_1.csv")

In [87]:
df1.groupby('STATION')['UNIT'].nunique()

STATION
1 AV               1
103 ST             3
110 ST             1
116 ST             3
116 ST-COLUMBIA    1
125 ST             4
135 ST             2
137 ST CITY COL    1
14 ST              3
14 ST-UNION SQ     1
145 ST             3
155 ST             2
157 ST             1
163 ST-AMSTERDM    1
168 ST             1
175 ST             1
18 ST              1
181 ST             2
190 ST             1
191 ST             1
2 AV               1
207 ST             1
215 ST             1
23 ST              6
28 ST              3
3 AV               1
33 ST              1
34 ST-HERALD SQ    2
34 ST-HUDSON YD    1
34 ST-PENN STA     4
42 ST-BRYANT PK    1
42 ST-PORT AUTH    2
47-50 STS ROCK     1
49 ST              1
5 AV/53 ST         1
5 AV/59 ST         1
5 AVE              1
50 ST              3
51 ST              1
57 ST              1
57 ST-7 AV         1
59 ST              3
59 ST COLUMBUS     1
6 AV               1
66 ST-LINCOLN      1
68ST-HUNTER CO     1
7 AV               3
72 ST              2
77 ST              2
79 ST              2
8 AV               2
8 ST-NYU           1
81 ST-MUSEUM       1
86 ST              5
96 ST              3
ASTOR PL           1
BLEECKER ST        1
BOWERY             1
BOWLING GREEN      2
BROAD ST           1
BROOKLYN BRIDGE    1
CANAL ST           5
CATHEDRAL PKWY     2
CENTRAL PK N110    1
CHAMBERS ST        3
CHRISTOPHER ST     2
CITY HALL          1
CORTLANDT ST       1
DELANCEY/ESSEX     1
DYCKMAN ST         2
EAST BROADWAY      1
FRANKLIN ST        1
FULTON ST          3
GRAND ST           2
GRD CNTRL-42 ST    4
HARLEM 148 ST      1
HOUSTON ST         1
INWOOD-207 ST      1
LEXINGTON AV/53    2
LEXINGTON AV/63    1
MARBLE HILL-225    1
PARK PLACE         2
PRINCE ST          1
RECTOR ST          2
ROOSEVELT ISLND    1
SOUTH FERRY        1
SPRING ST          2
TIMES SQ-42 ST     2
W 4 ST-WASH SQ     1
WALL ST            2
WHITEHALL S-FRY    1
WORLD TRADE CTR    1
WTC-CORTLANDT      1
Name: UNIT, dtype: int64

In [123]:
df1.DATETIME = pd.to_datetime(df1.DATETIME)
df1.sort_values(by=['STATION', 'SCP', 'UNIT', 'DATETIME'], inplace=True)

In [130]:
df1['NET_ENTRIES'] = df1.groupby(['STATION', 'SCP', 'UNIT'])['ENTRIES'].diff()
df1['NET_EXITS'] = df1.groupby(['STATION', 'SCP', 'UNIT'])['EXITS'].diff()

In [131]:
df1[(df1.STATION == '190 ST') & 
    ((df1.DATETIME == datetime.datetime.strptime('2018-12-09 11:00:00', '%Y-%m-%d %H:%M:%S')) |
     (df1.DATETIME == datetime.datetime.strptime('2018-12-09 07:00:00', '%Y-%m-%d %H:%M:%S')))]

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,ENTRIES,EXITS,DATETIME,NET_ENTRIES,NET_EXITS
3958900,N006A,R280,00-00-00,190 ST,A,IND,1.442539e+09,1.845235e+09,2018-12-09 07:00:00,-29.0,-22.0
3958899,N006A,R280,00-00-00,190 ST,A,IND,1.442539e+09,1.845235e+09,2018-12-09 11:00:00,-250.0,-73.0
3956751,N006A,R280,00-00-01,190 ST,A,IND,3.985540e+06,1.327283e+06,2018-12-09 07:00:00,25.0,14.0
3956750,N006A,R280,00-00-01,190 ST,A,IND,3.985693e+06,1.327303e+06,2018-12-09 11:00:00,153.0,20.0
3954601,N006A,R280,00-00-02,190 ST,A,IND,7.124714e+06,9.735020e+05,2018-12-09 07:00:00,17.0,9.0
3954600,N006A,R280,00-00-02,190 ST,A,IND,7.124859e+06,9.735080e+05,2018-12-09 11:00:00,145.0,6.0

In [92]:
df1 = df1.reindex(index=df1.index[::-1])

In [64]:
df1.sort_values('STATION', inplace=True)

In [98]:
# how many expected to be NAs - the very first record for each possible combination of STATION, SCP, UNIT
len(df1.groupby(['STATION', 'SCP', 'UNIT'])['ENTRIES'].max())

2233

In [99]:
# get the actual number of NA rows
len(df1[df1.isna().any(axis=1)])

2235

In [100]:
len(df1)

4644040

In [183]:
# drop the NA rows
df1.dropna(axis=0, inplace=True)

In [184]:
len(df1)

4641805

In [185]:
df1.drop(columns = ['LINENAME', 'DIVISION', 'ENTRIES', 'EXITS'], inplace=True)

In [186]:
df_final = df1.groupby(['STATION', 'DATETIME']).sum().reset_index()

In [187]:
len(df_final)

261164

In [188]:
num_corrupt_rows = len(df_final[(df_final.NET_ENTRIES < 0) | (df_final.NET_EXITS < 0)])

In [189]:
num_corrupt_rows

3444

In [190]:
df_final[(df_final.NET_ENTRIES < 0) | (df_final.NET_EXITS < 0)].STATION.nunique()

77

In [191]:
affected_dates = df_final[(df_final.NET_ENTRIES < 0) | (df_final.NET_EXITS < 0)].DATETIME.apply(lambda x: 
                                                                                        x.date()).unique().tolist()

In [192]:
len(df_final.DATETIME.apply(lambda x: x.date()).unique())

364

In [193]:
len(affected_dates)

364

In [194]:
print("%age of curropt data = ", num_corrupt_rows*100/len(df_final))

%age of curropt data =  1.3187116141581534

### 1.32% of rows from the data are curropt - EXCLUDING THEM FROM FINAL ANALYSIS
- 364/364 days affected with atleast one row corrupt
- 77/93 stations affected over the year

In [197]:
df_final.drop(axis=0, index=df_final[(df_final.NET_ENTRIES < 0) | (df_final.NET_EXITS < 0)].index, inplace=True)

In [198]:
len(df_final)

257720

In [199]:
93*6*365

203670

In [200]:
df_final.to_csv('cleaned_data_final.csv', index=False)

In [2]:
df_final = pd.read_csv('cleaned_data_final.csv')

In [6]:
df_final[df_final.STATION == '103 ST'].head(500)

     STATION             DATETIME  NET_ENTRIES  NET_EXITS
2281  103 ST  2018-12-08 00:00:00        141.0      213.0
2282  103 ST  2018-12-08 04:00:00        403.0      905.0
2283  103 ST  2018-12-08 08:00:00       1098.0     1749.0
2284  103 ST  2018-12-08 12:00:00       6313.0     3111.0
2285  103 ST  2018-12-08 16:00:00       6173.0     3679.0
2286  103 ST  2018-12-08 20:00:00       5366.0     4192.0
2287  103 ST  2018-12-09 00:00:00       2694.0     3138.0
2288  103 ST  2018-12-09 04:00:00        433.0      923.0
2289  103 ST  2018-12-09 08:00:00        732.0      685.0
2290  103 ST  2018-12-09 12:00:00       4208.0     2166.0
2291  103 ST  2018-12-09 16:00:00       5226.0     2990.0
2292  103 ST  2018-12-09 20:00:00       3796.0     3765.0
2293  103 ST  2018-12-10 00:00:00       1650.0     2166.0
2294  103 ST  2018-12-10 04:00:00        203.0      422.0
2295  103 ST  2018-12-10 08:00:00       3936.0     2306.0
2296  103 ST  2018-12-10 09:06:56       1689.0     1192.0
2297  103 ST  2018-12-10 09:27:40        350.0      323.0
2298  103 ST  2018-12-10 12:00:00       7575.0     2901.0
2299  103 ST  2018-12-10 16:00:00       7027.0     4224.0
2300  103 ST  2018-12-10 20:00:00       8293.0     7006.0
2301  103 ST  2018-12-11 00:00:00       2285.0     3288.0
2302  103 ST  2018-12-11 04:00:00        264.0      542.0
2303  103 ST  2018-12-11 08:00:00       4186.0     2357.0
2304  103 ST  2018-12-11 12:00:00      10032.0     4379.0
2305  103 ST  2018-12-11 16:00:00       6861.0     4589.0
2306  103 ST  2018-12-11 20:00:00       8789.0     6958.0
2307  103 ST  2018-12-12 00:00:00       2481.0     3602.0
2308  103 ST  2018-12-12 04:00:00        249.0      631.0
2309  103 ST  2018-12-12 08:00:00       4140.0     2295.0
2310  103 ST  2018-12-12 12:00:00      10091.0     4488.0
2311  103 ST  2018-12-12 16:00:00       7148.0     4650.0
2312  103 ST  2018-12-12 20:00:00       8545.0     6695.0
2313  103 ST  2018-12-13 00:00:00       2410.0     3562.0
2314  103 ST  2018-12-13 04:00:00        273.0      643.0
2315  103 ST  2018-12-13 08:00:00       2382.0     1994.0
2316  103 ST  2018-12-13 12:00:00      11575.0     4741.0
2317  103 ST  2018-12-13 16:00:00       7452.0     4356.0
2318  103 ST  2018-12-13 20:00:00       8398.0     6877.0
2319  103 ST  2018-12-14 00:00:00       2612.0     3671.0
2320  103 ST  2018-12-14 04:00:00        289.0      689.0
2321  103 ST  2018-12-14 08:00:00       3815.0     2307.0
2322  103 ST  2018-12-14 12:00:00       9619.0     4370.0
2323  103 ST  2018-12-14 16:00:00       7653.0     4686.0
2324  103 ST  2018-12-14 20:00:00       8335.0     6716.0
2325  103 ST  2018-12-15 00:00:00       3242.0     3638.0
2326  103 ST  2018-12-15 04:00:00        448.0      933.0
2327  103 ST  2018-12-15 08:00:00       1065.0      799.0
2328  103 ST  2018-12-15 12:00:00       4699.0     2381.0
2329  103 ST  2018-12-15 16:00:00       5932.0     3542.0
2330  103 ST  2018-12-15 20:00:00       5321.0     4215.0
2331  103 ST  2018-12-16 00:00:00       2793.0     2990.0
2332  103 ST  2018-12-16 04:00:00        532.0     1010.0
2333  103 ST  2018-12-16 08:00:00        733.0      525.0
2334  103 ST  2018-12-16 12:00:00       3855.0     1746.0
2335  103 ST  2018-12-16 16:00:00       4862.0     3155.0
2336  103 ST  2018-12-16 20:00:00       3815.0     3504.0
2337  103 ST  2018-12-17 00:00:00       1678.0     2094.0
2338  103 ST  2018-12-17 04:00:00        233.0      369.0
2339  103 ST  2018-12-17 08:00:00       4034.0     2272.0
2340  103 ST  2018-12-17 12:00:00       9453.0     4217.0
2341  103 ST  2018-12-17 16:00:00       6966.0     4517.0
2342  103 ST  2018-12-17 20:00:00       8210.0     6824.0
2343  103 ST  2018-12-18 00:00:00       2500.0     3387.0
2344  103 ST  2018-12-18 04:00:00        281.0      565.0
2345  103 ST  2018-12-18 08:00:00       4082.0     2337.0
2346  103 ST  2018-12-18 12:00:00       9582.0     4274.0
2347  103 ST  2018-12-18 16:00:00       7092.0     4518.0
2348  103 ST  2018-12-18 20:00:00       8527.0     6867.0
2349  103 ST  2018-12-19 00:00:00       2388.0     3451.0
2350  103 ST  2018-12-19 04:00:00        254.0      553.0
2351  103 ST  2018-12-19 08:00:00       3805.0     2316.0
2352  103 ST  2018-12-19 12:00:00       9783.0     4356.0
2353  103 ST  2018-12-19 16:00:00       7234.0     4743.0
2354  103 ST  2018-12-19 20:00:00       8432.0     6624.0
2355  103 ST  2018-12-20 00:00:00       2628.0     3424.0
2356  103 ST  2018-12-20 04:00:00        311.0      622.0
2357  103 ST  2018-12-20 08:00:00       3741.0     2261.0
2358  103 ST  2018-12-20 12:00:00       9314.0     4258.0
2359  103 ST  2018-12-20 16:00:00       7654.0     4692.0
2360  103 ST  2018-12-20 20:00:00       8400.0     6845.0
2361  103 ST  2018-12-21 00:00:00       2419.0     3410.0
2362  103 ST  2018-12-21 04:00:00        338.0      638.0
2363  103 ST  2018-12-21 08:00:00       3431.0     2036.0
2364  103 ST  2018-12-21 12:00:00       8517.0     4093.0
2365  103 ST  2018-12-21 16:00:00       7651.0     4716.0
2366  103 ST  2018-12-21 20:00:00       7172.0     5805.0
2367  103 ST  2018-12-22 00:00:00       2802.0     3025.0
2368  103 ST  2018-12-22 04:00:00        389.0      838.0
2369  103 ST  2018-12-22 08:00:00        526.0      287.0
2370  103 ST  2018-12-22 12:00:00       4835.0     2533.0
2371  103 ST  2018-12-22 16:00:00       5739.0     3255.0
2372  103 ST  2018-12-22 20:00:00       4735.0     3742.0
2373  103 ST  2018-12-23 00:00:00       2351.0     2717.0
2374  103 ST  2018-12-23 04:00:00        377.0      814.0
2375  103 ST  2018-12-23 08:00:00        734.0      587.0
2376  103 ST  2018-12-23 12:00:00       3678.0     1555.0
2377  103 ST  2018-12-23 16:00:00       4815.0     2805.0
2378  103 ST  2018-12-23 20:00:00       3866.0     3499.0
2379  103 ST  2018-12-24 00:00:00       1807.0     2342.0
2380  103 ST  2018-12-24 04:00:00        285.0      583.0
2381  103 ST  2018-12-24 08:00:00       1594.0     1243.0
2382  103 ST  2018-12-24 12:00:00       5160.0     2601.0
2383  103 ST  2018-12-24 16:00:00       5781.0     3831.0
2384  103 ST  2018-12-24 20:00:00       4609.0     4138.0
2385  103 ST  2018-12-25 00:00:00       2049.0     2051.0
2386  103 ST  2018-12-25 04:00:00        327.0      578.0
2387  103 ST  2018-12-25 08:00:00        551.0      507.0
2388  103 ST  2018-12-25 12:00:00       2451.0     1159.0
2389  103 ST  2018-12-25 16:00:00       3264.0     1927.0
2390  103 ST  2018-12-25 20:00:00       3142.0     2771.0
2391  103 ST  2018-12-26 00:00:00       1441.0     2054.0
2392  103 ST  2018-12-26 04:00:00        240.0      468.0
2393  103 ST  2018-12-26 08:00:00       1906.0     1260.0
2394  103 ST  2018-12-26 12:00:00       5847.0     2774.0
2395  103 ST  2018-12-26 16:00:00       5934.0     3541.0
2396  103 ST  2018-12-26 20:00:00       5806.0     4791.0
2397  103 ST  2018-12-27 00:00:00       1981.0     2724.0
2398  103 ST  2018-12-27 04:00:00        253.0      522.0
2399  103 ST  2018-12-27 08:00:00       2207.0     1414.0
2400  103 ST  2018-12-27 12:00:00       6843.0     3278.0
2401  103 ST  2018-12-27 16:00:00       6241.0     4002.0
2402  103 ST  2018-12-27 20:00:00       6458.0     5198.0
2403  103 ST  2018-12-28 00:00:00       2180.0     2954.0
2404  103 ST  2018-12-28 04:00:00        297.0      639.0
2405  103 ST  2018-12-28 08:00:00       2048.0     1337.0
2406  103 ST  2018-12-28 12:00:00       6448.0     3233.0
2407  103 ST  2018-12-28 16:00:00       5951.0     3912.0
2408  103 ST  2018-12-28 20:00:00       6409.0     4899.0
2409  103 ST  2018-12-29 00:00:00       2465.0     2806.0
2410  103 ST  2018-12-29 04:00:00        390.0      862.0
2411  103 ST  2018-12-29 08:00:00       1062.0      788.0
2412  103 ST  2018-12-29 12:00:00       4428.0     2044.0
2413  103 ST  2018-12-29 16:00:00       5538.0     3080.0
2414  103 ST  2018-12-29 20:00:00       4710.0     4095.0
2415  103 ST  2018-12-30 00:00:00       2369.0     2908.0
2416  103 ST  2018-12-30 04:00:00        423.0      881.0
2417  103 ST  2018-12-30 08:00:00        771.0      576.0
2418  103 ST  2018-12-30 12:00:00       3713.0     1503.0
2419  103 ST  2018-12-30 16:00:00       5007.0     2716.0
2420  103 ST  2018-12-30 20:00:00       4197.0     3350.0
2421  103 ST  2018-12-31 00:00:00       1932.0     2438.0
2422  103 ST  2018-12-31 04:00:00        314.0      572.0
2423  103 ST  2018-12-31 08:00:00       1712.0     1209.0
2424  103 ST  2018-12-31 12:00:00       5856.0     2961.0
2425  103 ST  2018-12-31 16:00:00       6217.0     4224.0
2426  103 ST  2018-12-31 20:00:00       5512.0     4421.0
2427  103 ST  2019-01-01 00:00:00       3402.0     2374.0
2428  103 ST  2019-01-01 04:00:00       1055.0     1838.0
2429  103 ST  2019-01-01 08:00:00        661.0      743.0
2430  103 ST  2019-01-01 12:00:00       2545.0     1213.0
2431  103 ST  2019-01-01 16:00:00       4485.0     2426.0
2432  103 ST  2019-01-01 20:00:00       3408.0     3088.0
2433  103 ST  2019-01-02 00:00:00       1575.0     2019.0
2434  103 ST  2019-01-02 04:00:00        224.0      458.0
2435  103 ST  2019-01-02 08:00:00       3354.0     1810.0
2436  103 ST  2019-01-02 12:00:00       8179.0     3943.0
2437  103 ST  2019-01-02 16:00:00       6633.0     4043.0
2438  103 ST  2019-01-02 20:00:00       7015.0     6241.0
2439  103 ST  2019-01-03 00:00:00       2119.0     2964.0
2440  103 ST  2019-01-03 04:00:00        280.0      525.0
2441  103 ST  2019-01-03 08:00:00       3500.0     2051.0
2442  103 ST  2019-01-03 12:00:00       8713.0     4261.0
2443  103 ST  2019-01-03 16:00:00       6888.0     4308.0
2444  103 ST  2019-01-03 20:00:00       7599.0     6600.0
2445  103 ST  2019-01-04 00:00:00       2212.0     3069.0
2446  103 ST  2019-01-04 04:00:00        263.0      554.0
2447  103 ST  2019-01-04 08:00:00       3425.0     2062.0
2448  103 ST  2019-01-04 12:00:00       8860.0     4554.0
2449  103 ST  2019-01-04 16:00:00       7370.0     4412.0
2450  103 ST  2019-01-04 20:00:00       7505.0     6276.0
2451  103 ST  2019-01-05 00:00:00       2661.0     3002.0
2452  103 ST  2019-01-05 04:00:00        426.0      901.0
2453  103 ST  2019-01-05 08:00:00        948.0     2021.0
2454  103 ST  2019-01-05 12:00:00       5245.0     2251.0
2455  103 ST  2019-01-05 16:00:00       5201.0     3208.0
2456  103 ST  2019-01-05 20:00:00       4725.0     3530.0
2457  103 ST  2019-01-06 00:00:00       2261.0     2527.0
2458  103 ST  2019-01-06 04:00:00        375.0      868.0
2459  103 ST  2019-01-06 08:00:00        661.0      732.0
2460  103 ST  2019-01-06 12:00:00       3336.0     1724.0
2461  103 ST  2019-01-06 16:00:00       4747.0     3117.0
2462  103 ST  2019-01-06 20:00:00       3756.0     3496.0
2463  103 ST  2019-01-07 00:00:00       1636.0     2072.0
2464  103 ST  2019-01-07 04:00:00        226.0      379.0
2465  103 ST  2019-01-07 08:00:00       3774.0     2236.0
2466  103 ST  2019-01-07 12:00:00       8777.0     4252.0
2467  103 ST  2019-01-07 16:00:00       6512.0     4460.0
2468  103 ST  2019-01-07 20:00:00       7687.0     6794.0
2469  103 ST  2019-01-08 00:00:00       2058.0     2673.0
2470  103 ST  2019-01-08 04:00:00        264.0      468.0
2471  103 ST  2019-01-08 08:00:00       3973.0     2339.0
2472  103 ST  2019-01-08 12:00:00       9093.0     4337.0
2473  103 ST  2019-01-08 16:00:00       6385.0     4246.0
2474  103 ST  2019-01-08 20:00:00       8142.0     6621.0
2475  103 ST  2019-01-09 00:00:00       2259.0     2979.0
2476  103 ST  2019-01-09 04:00:00        261.0      489.0
2477  103 ST  2019-01-09 08:00:00       3897.0     2369.0
2478  103 ST  2019-01-09 12:00:00       9257.0     4432.0
2479  103 ST  2019-01-09 16:00:00       6870.0     4508.0
2480  103 ST  2019-01-09 20:00:00       8004.0     6707.0
2481  103 ST  2019-01-10 00:00:00       2233.0     3101.0
2482  103 ST  2019-01-10 04:00:00        157.0      306.0
2483  103 ST  2019-01-10 08:00:00       4065.0     2528.0
2484  103 ST  2019-01-10 12:00:00       9322.0     4375.0
2485  103 ST  2019-01-10 16:00:00       6873.0     4505.0
2486  103 ST  2019-01-10 20:00:00       8298.0     6878.0
2487  103 ST  2019-01-11 00:00:00       2297.0     3049.0
2488  103 ST  2019-01-11 04:00:00        257.0      500.0
2489  103 ST  2019-01-11 08:00:00       3787.0     2267.0
2490  103 ST  2019-01-11 12:00:00       8850.0     4383.0
2491  103 ST  2019-01-11 16:00:00       7097.0     4627.0
2492  103 ST  2019-01-11 20:00:00       7839.0     6595.0
2493  103 ST  2019-01-12 00:00:00       2658.0     2998.0
2494  103 ST  2019-01-12 04:00:00        335.0      668.0
2495  103 ST  2019-01-12 08:00:00       1015.0      763.0
2496  103 ST  2019-01-12 12:00:00       4238.0     2287.0
2497  103 ST  2019-01-12 16:00:00       5434.0     3090.0
2498  103 ST  2019-01-12 20:00:00       4660.0     3869.0
2499  103 ST  2019-01-13 00:00:00       2243.0     2509.0
2500  103 ST  2019-01-13 04:00:00        358.0      745.0
2501  103 ST  2019-01-13 08:00:00        695.0      623.0
2502  103 ST  2019-01-13 12:00:00       3374.0     1490.0
2503  103 ST  2019-01-13 16:00:00       4611.0     2788.0
2504  103 ST  2019-01-13 20:00:00       3372.0     3355.0
2505  103 ST  2019-01-14 00:00:00       1570.0     1921.0
2506  103 ST  2019-01-14 04:00:00        250.0      371.0
2507  103 ST  2019-01-14 08:00:00       3923.0     2277.0
2508  103 ST  2019-01-14 12:00:00       8966.0     4325.0
2509  103 ST  2019-01-14 16:00:00       6418.0     4360.0
2510  103 ST  2019-01-14 20:00:00       7738.0     6925.0
2511  103 ST  2019-01-15 00:00:00       2161.0     2648.0
2512  103 ST  2019-01-15 04:00:00        235.0      450.0
2513  103 ST  2019-01-15 08:00:00       4122.0     2392.0
2514  103 ST  2019-01-15 08:25:47        684.0      399.0
2515  103 ST  2019-01-15 12:00:00       8504.0     4062.0
2516  103 ST  2019-01-15 16:00:00       6568.0     4333.0
2517  103 ST  2019-01-15 20:00:00       8213.0     6790.0
2518  103 ST  2019-01-16 00:00:00       2263.0     2969.0
2519  103 ST  2019-01-16 04:00:00        233.0      360.0
2520  103 ST  2019-01-16 08:00:00       3975.0     2365.0
2521  103 ST  2019-01-16 12:00:00       9503.0     4439.0
2522  103 ST  2019-01-16 16:00:00       6808.0     4582.0
2523  103 ST  2019-01-16 20:00:00       8134.0     6569.0
2524  103 ST  2019-01-17 00:00:00       2312.0     3102.0
2525  103 ST  2019-01-17 04:00:00        265.0      510.0
2526  103 ST  2019-01-17 08:00:00       3907.0     2038.0
2527  103 ST  2019-01-17 12:00:00       9441.0     4596.0
2528  103 ST  2019-01-17 16:00:00       6708.0     4497.0
2529  103 ST  2019-01-17 20:00:00       8191.0     6714.0
2530  103 ST  2019-01-18 00:00:00       2306.0     3147.0
2531  103 ST  2019-01-18 04:00:00        237.0      554.0
2532  103 ST  2019-01-18 08:00:00       3650.0     2229.0
2533  103 ST  2019-01-18 12:00:00       8747.0     4198.0
2534  103 ST  2019-01-18 16:00:00       7117.0     4399.0
2535  103 ST  2019-01-18 20:00:00       7750.0     6260.0
2536  103 ST  2019-01-19 00:00:00       2667.0     2807.0
2537  103 ST  2019-01-19 04:00:00        383.0      798.0
2538  103 ST  2019-01-19 08:00:00       1044.0      778.0
2539  103 ST  2019-01-19 12:00:00       4340.0     2189.0
2540  103 ST  2019-01-19 16:00:00       5364.0     3308.0
2541  103 ST  2019-01-19 20:00:00       4572.0     3532.0
2542  103 ST  2019-01-20 00:00:00       2108.0     2435.0
2543  103 ST  2019-01-20 04:00:00        351.0      635.0
2544  103 ST  2019-01-20 08:00:00        681.0     1024.0
2545  103 ST  2019-01-20 12:00:00       3706.0     1391.0
2546  103 ST  2019-01-20 16:00:00       4115.0     2461.0
2547  103 ST  2019-01-20 20:00:00       3290.0     2973.0
2548  103 ST  2019-01-21 00:00:00       1558.0     1799.0
2549  103 ST  2019-01-21 04:00:00        203.0      380.0
2550  103 ST  2019-01-21 08:00:00       1421.0      924.0
2551  103 ST  2019-01-21 12:00:00       4250.0     2083.0
2552  103 ST  2019-01-21 16:00:00       4384.0     2950.0
2553  103 ST  2019-01-21 20:00:00       3862.0     3824.0
2554  103 ST  2019-01-22 00:00:00       1352.0     1735.0
2555  103 ST  2019-01-22 04:00:00        161.0      278.0
2556  103 ST  2019-01-22 08:00:00       3612.0     2187.0
2557  103 ST  2019-01-22 08:39:11       1140.0      203.0
2558  103 ST  2019-01-22 12:00:00       7907.0     3802.0
2559  103 ST  2019-01-22 16:00:00       6387.0     4143.0
2560  103 ST  2019-01-22 20:00:00       7767.0     6274.0
2561  103 ST  2019-01-23 00:00:00       1944.0     2900.0
2562  103 ST  2019-01-23 04:00:00        207.0      381.0
2563  103 ST  2019-01-23 08:00:00       3598.0     2326.0
2564  103 ST  2019-01-23 12:00:00       9323.0     4349.0
2565  103 ST  2019-01-23 16:00:00       6574.0     4396.0
2566  103 ST  2019-01-23 20:00:00       8177.0     6489.0
2567  103 ST  2019-01-24 00:00:00       1965.0     2950.0
2568  103 ST  2019-01-24 04:00:00        204.0      488.0
2569  103 ST  2019-01-24 08:00:00       3637.0     2216.0
2570  103 ST  2019-01-24 12:00:00       8954.0     3390.0
2571  103 ST  2019-01-24 16:00:00       6730.0     4939.0
2572  103 ST  2019-01-24 20:00:00       7821.0     6369.0
2573  103 ST  2019-01-25 00:00:00       1982.0     2990.0
2574  103 ST  2019-01-25 04:00:00        231.0      484.0
2575  103 ST  2019-01-25 08:00:00       3451.0     2386.0
2576  103 ST  2019-01-25 08:12:32        287.0       80.0
2577  103 ST  2019-01-25 12:00:00       8796.0     4081.0
2578  103 ST  2019-01-25 16:00:00       7228.0     4548.0
2579  103 ST  2019-01-25 20:00:00       7894.0     6390.0
2580  103 ST  2019-01-26 00:00:00       2464.0     3195.0
2581  103 ST  2019-01-26 04:00:00        298.0      755.0
2582  103 ST  2019-01-26 08:00:00       1014.0      804.0
2583  103 ST  2019-01-26 12:00:00       4312.0     2429.0
2584  103 ST  2019-01-26 16:00:00       5578.0     3250.0
2585  103 ST  2019-01-26 20:00:00       4731.0     3838.0
2586  103 ST  2019-01-27 00:00:00       1957.0     2518.0
2587  103 ST  2019-01-27 04:00:00        323.0      745.0
2588  103 ST  2019-01-27 08:00:00        669.0      564.0
2589  103 ST  2019-01-27 12:00:00       3441.0     1593.0
2590  103 ST  2019-01-27 16:00:00       4540.0     2946.0
2591  103 ST  2019-01-27 20:00:00       3565.0     3418.0
2592  103 ST  2019-01-28 00:00:00       1411.0     2001.0
2593  103 ST  2019-01-28 04:00:00        193.0      327.0
2594  103 ST  2019-01-28 08:00:00       3594.0     2269.0
2595  103 ST  2019-01-28 12:00:00       9090.0     4171.0
2596  103 ST  2019-01-28 16:00:00       6409.0     4152.0
2597  103 ST  2019-01-28 20:00:00       7664.0     6714.0
2598  103 ST  2019-01-29 00:00:00       2229.0     2928.0
2599  103 ST  2019-01-29 04:00:00        248.0      476.0
2600  103 ST  2019-01-29 08:00:00       3950.0     2385.0
2601  103 ST  2019-01-29 12:00:00       9240.0     4459.0
2602  103 ST  2019-01-29 16:00:00       6638.0     4450.0
2603  103 ST  2019-01-29 20:00:00       8069.0     6911.0
2604  103 ST  2019-01-30 00:00:00       2153.0     2895.0
2605  103 ST  2019-01-30 04:00:00        194.0      392.0
2606  103 ST  2019-01-30 08:00:00       4041.0     2209.0
2607  103 ST  2019-01-30 12:00:00       9308.0     4382.0
2608  103 ST  2019-01-30 15:28:08        701.0      511.0
2609  103 ST  2019-01-30 15:31:05         14.0        0.0
2610  103 ST  2019-01-30 16:00:00       6145.0     4067.0
2611  103 ST  2019-01-30 20:00:00       7478.0     7001.0
2612  103 ST  2019-01-31 00:00:00       1978.0     2644.0
2613  103 ST  2019-01-31 04:00:00        180.0      362.0
2614  103 ST  2019-01-31 08:00:00       3612.0     1947.0
2615  103 ST  2019-01-31 12:00:00       8506.0     4021.0
2616  103 ST  2019-01-31 16:00:00       5878.0     3904.0
2617  103 ST  2019-01-31 20:00:00       7302.0     6478.0
2618  103 ST  2019-02-01 00:00:00       2017.0     2764.0
2619  103 ST  2019-02-01 04:00:00        233.0      424.0
2620  103 ST  2019-02-01 08:00:00       2241.0     1809.0
2621  103 ST  2019-02-01 11:36:35       1687.0      419.0
2622  103 ST  2019-02-01 12:00:00       8199.0     4869.0
2623  103 ST  2019-02-01 16:00:00       6830.0     4297.0

In [7]:
df = pd.read_csv('/Users/candide/Acads/EDAV/final project/turnstile_data/20181215.csv')

In [54]:
df.head(10)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/08/2018,03:00:00,REGULAR,6863293,2327473
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/08/2018,07:00:00,REGULAR,6863304,2327489
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/08/2018,11:00:00,REGULAR,6863387,2327546
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/08/2018,15:00:00,REGULAR,6863612,2327582
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/08/2018,19:00:00,REGULAR,6863951,2327648
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/08/2018,23:00:00,REGULAR,6864127,2327668
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/09/2018,03:00:00,REGULAR,6864177,2327678
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/09/2018,07:00:00,REGULAR,6864185,2327684
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/09/2018,11:00:00,REGULAR,6864229,2327720
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/09/2018,15:00:00,REGULAR,6864373,2327772

In [22]:
df[(df.STATION == '103 ST') & (df.DATE == '12/08/2018')].groupby('TIME').sum()

,ENTRIES,EXITS
TIME,,
00:00:00,156818704,602006085
04:00:00,156819107,602006990
08:00:00,156820205,602008739
12:00:00,156826518,602011850
16:00:00,156832691,602015529
20:00:00,156838057,602019721

In [23]:
df_final[(df_final.STATION == '103 ST') & (df_final.DATETIME == '2019-03-21 17:00:00')]

     STATION             DATETIME   NET_ENTRIES     NET_EXITS
2924  103 ST  2019-03-21 17:00:00  2.088511e+09  1.684288e+09

In [51]:
import matplotlib.pyplot as plt
plt.figure(figsize=(20,20))
len(df_final[df_final.NET_ENTRIES > 10000])

21380

In [53]:
df_final[df_final.NET_EXITS].describe()

        NET_ENTRIES     NET_EXITS
count  2.577200e+05  2.577200e+05
mean   6.902804e+04  5.078510e+04
std    8.737631e+06  6.671706e+06
min    0.000000e+00  0.000000e+00
25%    4.200000e+02  3.450000e+02
50%    1.596000e+03  1.272000e+03
75%    4.316000e+03  3.618000e+03
max    2.088511e+09  1.684288e+09